[package]
name = "i18n-greeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
byteorder = "1.4.3"
llvm-sys = "120.2.6"
wasmer = "3.1.1"
wasmer-compiler-llvm = "3.1.1"
