[package]
name = "i18n-greeter"
version = "0.1.0"
edition = "2021"
authors = ["JP Moresmau <jp@slight.dev>"]

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
wasmtime = {version = "7.0.0", features= ["component-model"]}
