[package]
name = "english-rs"
version = "0.1.0"
authors = ["JP Moresmau <jp@slight.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.4.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
